export { default as AppLogo } from "../assets/images/applogo.png";
export { default as CardImageFour } from "../assets/images/frames.jpg";
export { default as CardImagePlant } from "../assets/images/plant.avif";
export { default as CardImageBook } from "../assets/images/book.jpg";
export { default as CardImageCard } from "../assets/images/card.webp";
export { default as CardImageFrame } from "../assets/images/frame.jpg";
export { default as CardImageCards } from "../assets/images/cards.webp";
export { default as CardImageGift } from "../assets/images/gift.webp";
export { default as CUSTOM } from"../assets/images/custom.svg";
export { default as TableImage } from "../assets/images/tablephoto.png";
export { default as NEWLAND } from "../assets/images/newland.png";
export { default as NEWLAND2 } from "../assets/images/land.png";
export { default as IMAGE1 } from "../assets/images/one.png";
export { default as IMAGE2 } from "../assets/images/two.png";
export { default as IMAGE3 } from "../assets/images/three.png";
export { default as IMAGE4 } from "../assets/images/four.png";
export { default as IMAGE5 } from "../assets/images/five.png";
export { default as IMAGE6 } from "../assets/images/six.png";
export { default as IMAGE7 } from "../assets/images/seven.png";
export { default as IMAGE8 } from "../assets/images/eight.png";
export { default as IMAGE9 } from "../assets/images/nine.png";
export { default as IMAGE10 } from "../assets/images/ten.png";
export { default as IMAGE11 } from "../assets/images/11.png";
export { default as IMAGE12 } from "../assets/images/12.png";
export { default as IMAGE13 } from "../assets/images/13.png";
export { default as SIGNUP_IMAGE } from "../assets/images/signup.jpg";
export { default as SIGNUP } from "../assets/images/signs.png";
export { default as LOCATION } from "../assets/images/location.png";
export { default as DOWNLOAD } from "../assets/images/download.svg";
export { default as HELPIMAGE } from "../assets/images/helpgif.gif";
export { default as FRIENDSCARD } from "../assets/images/friendscard.jpg";
export { default as MENUCARD } from "../assets/images/menucard.webp";
export { default as IDCARD1 } from "../assets/images/idcard1.jpeg";
export { default as IDCARD2 } from "../assets/images/idcard2.jpeg";
export { default as IDCARD3 } from "../assets/images/idcard3.jpeg";
export { default as IDCARD4 } from "../assets/images/idcard4.jpeg";
export { default as GREETING_ONE } from "../assets/images/Greeting1.png";
export { default as GREETING_TWO } from "../assets/images/Greeting2.png";
export { default as GREETING_THREE } from "../assets/images/Greeting3.png";
export { default as GREETING_FOUR } from "../assets/images/Greeting4.png";
export { default as preview } from "../assets/images/preview.png";
export { default as preview1 } from "../assets/images/preview1.png";
export { default as preview2 } from "../assets/images/preview2.png";
export { default as preview3 } from "../assets/images/preview3.png";
export { default as xerox } from "../assets/images/xerox.png";
export { default as xerox1 } from "../assets/images/xerox1.png";
export { default as xerox2 } from "../assets/images/xerox2.png";
export { default as xerox3 } from "../assets/images/xerox3.png";
export { default as REGISTER_ONE } from "../assets/images/Register1.jpeg";
export { default as REGISTER_TWO } from "../assets/images/Register2.jpeg";
export { default as REGISTER_THREE } from "../assets/images/Register3.jpeg";
export { default as REGISTER_FOUR } from "../assets/images/Register4.jpeg";
export { default as TC_ONE } from "../assets/images/tc1.jpg";
export { default as TC_TWO } from "../assets/images/tc2.jpg";
export { default as TC_THREE } from "../assets/images/tc3.jpg";
export { default as TC_FOUR } from "../assets/images/tc5.jpeg";
export { default as BAG_ONE } from "../assets/images/bag1.png";
export { default as BAG_TWO } from "../assets/images/bag2.png";
export { default as BAG_THREE } from "../assets/images/bag4.jpeg";
export { default as BAG_FOUR } from "../assets/images/bag4.png";
export { default as BANNER_ONE } from "../assets/images/banner1.jpeg";
export { default as BANNER_TWO } from "../assets/images/banner2.png";
export { default as BANNER_THREE } from "../assets/images/banner3.png";
export { default as BANNER_FOUR } from "../assets/images/banner4.jpeg";
export { default as CALENDER_ONE } from "../assets/images/calender1.jpeg";
export { default as CALENDER_TWO } from "../assets/images/calender2.jpeg";
export { default as CALENDER_THREE } from "../assets/images/calender3.jpeg";
export { default as CALENDER_FOUR } from "../assets/images/calender4.jpeg";
export { default as MENU_ONE } from "../assets/images/menu1.png";
export { default as MENU_TWO } from "../assets/images/menu2.png";
export { default as MENU_THREE } from "../assets/images/menu3.png";
export { default as MENU_FOUR } from "../assets/images/menu4.png";
export { default as BOOK1 } from "../assets/images/book1.avif";
export { default as BOOK2 } from "../assets/images/book2.png";
export { default as BOOK3 } from "../assets/images/book3.png";
export { default as BOOK4 } from "../assets/images/book4.jpg";
export { default as PRINT1 } from "../assets/images/print1.png";
export { default as PRINT2 } from "../assets/images/print2.png";
export { default as PRINT3 } from "../assets/images/print3.png";
export { default as PRINT4 } from "../assets/images/print4.png";
export { default as CARTLOGIN } from "../assets/images/cartlogin.png";
export { default as RUBBERSTAMP } from "../assets/images/rubber_stamp.jpg";
export {default as STAMP1} from "../assets/images/stamp1.png";
export {default as STAMP2} from "../assets/images/stamp2.png";
export {default as STAMP3} from "../assets/images/stamp3.png";
export {default as STAMP4} from "../assets/images/stamp4.png";
export {default as BILLS} from "../assets/images/bills.png";
export {default as LAPTOP} from "../assets/images/laptop.png";
export {default as GSTS} from "../assets/images/gsts.jpg";
export {default as INVOICES} from "../assets/images/invoices.png";
export {default as ADMINBG} from "../assets/images/adminbg.jpg";
export {default as ADMINHELP} from "../assets/images/illustration.png";
export {default as ADMINSETTING}from "../assets/images/remove.png";
export {default as CREATE}from "../assets/images/create.webp";
export {default as AUTO}from "../assets/images/auto.png";
export {default as PAYMENT}from "../assets/images/payment.webp";
export {default as INVOICE1} from "../assets/images/invoice1.jpg";
export { default as LOGIN_BACK } from "../assets/images/loginbacks.jpg";
